version: '2'

networks:
  fabric:

services:
  
  ca.oem.rms.com:
    image: hyperledger/fabric-ca
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-oem
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports: 
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/rms.com/oem/ca:/etc/hyperledger/fabric-ca-server
    container_name: ca.oem.rms.com
    networks:
      - fabric

  ca.client.rms.com:
    image: hyperledger/fabric-ca
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-client
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports: 
      - 8054:8054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/rms.com/client/ca:/etc/hyperledger/fabric-ca-server
    container_name: ca.client.rms.com
    networks:
      - fabric

  ca.insurance.rms.com:
    image: hyperledger/fabric-ca
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-insurance
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports: 
      - 9054:9054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/rms.com/insurance/ca:/etc/hyperledger/fabric-ca-server
    container_name: ca.insurance.rms.com
    networks:
      - fabric